#!/usr/bin/env python3
"""Independent Laurent reconstruction of the finite MP2 base certificates.

No producer imports. Actual triples are generated by the original scalar
mutation, not the normalized-state recurrence in the certificate producer.
The parameter polynomials are expanded directly after x=q+q^-1.
"""
from fractions import Fraction as F
from itertools import product
from math import comb
from pathlib import Path
import hashlib
import json
import gzip

HERE = Path(__file__).resolve().parent
DIM = 3  # q exponent, unit-cube u exponent, unit-cube v exponent
ZERO = (0, 0, 0)


def constant(a):
    return {ZERO: F(a)} if a else {}


def plus(*ps):
    out = {}
    for p in ps:
        for m, a in p.items():
            out[m] = out.get(m, F(0)) + a
    return {m: a for m, a in out.items() if a}


def times(p, q):
    out = {}
    for m, a in p.items():
        for n, b in q.items():
            k = tuple(m[i] + n[i] for i in range(DIM))
            out[k] = out.get(k, F(0)) + a * b
    return {m: a for m, a in out.items() if a}


def scaled(p, a):
    return {m: F(a) * b for m, b in p.items() if a * b}


def minus(p, q):
    return plus(p, scaled(q, -1))


def power(p, n):
    out = constant(1)
    for _ in range(n):
        out = times(out, p)
    return out


def original_mutation(X, Y, C, x):
    y = plus(x, constant(1))
    U = minus(minus(scaled(times(times(y, X), C), 3),
                    times(x, plus(X, C))), Y)
    V = minus(minus(scaled(times(times(y, Y), C), 3),
                    times(x, plus(Y, C))), X)
    return U, V


def ordinary_coeffs(p):
    assert all(u == v == 0 and n >= 0 for n, u, v in p)
    d = max((m[0] for m in p), default=0)
    return [p.get((n, 0, 0), F(0)) for n in range(d + 1)]


def quotient_y(p):
    # Exact division by x+1, performed in ordinary x before Laurent substitution.
    a = ordinary_coeffs(p)
    q = [F(0)] * (len(a) - 1)
    carry = F(0)
    for n in range(len(a) - 1, 0, -1):
        q[n - 1] = a[n] - carry
        carry = q[n - 1]
    assert a[0] == carry
    return {(n, 0, 0): v for n, v in enumerate(q) if v}


LAURENT_X = {(1, 0, 0): F(1), (-1, 0, 0): F(1)}
LAURENT_Y = plus(LAURENT_X, constant(1))


def laurent(p):
    out = {}
    for (n, u, v), a in p.items():
        assert u == v == 0
        out = plus(out, scaled(power(LAURENT_X, n), a))
    return out


def row(p, n):
    return {(0, u, v): a for (k, u, v), a in p.items() if k == n}


def tensor(p):
    """Full first-two-row minors; only their character-index relabeling is used."""
    d = max((abs(n) for n, _, _ in p), default=0)
    xp = times(LAURENT_X, p)
    out = {}
    for k in range(d + 2):
        for ell in range(k + 1, d + 2):
            value = minus(times(row(p, k), row(xp, ell)),
                          times(row(p, ell), row(xp, k)))
            if value:
                a, b = k + ell - 1, ell - k - 1
                out[a, b] = value
                if k:
                    out[b, a] = value
    return out


def tensor_minus(A, B, scalar):
    return {key: p for key in set(A) | set(B)
            if (p := minus(A.get(key, {}), scaled(B.get(key, {}), scalar)))}


def defect(p, n):
    h0, hm, hp, hpp = (row(p, j) for j in [n, abs(n - 1), n + 1, n + 2])
    return plus(times(h0, h0), scaled(times(hm, hp), -1),
                scaled(times(hp, hp), -1), times(h0, hpp))


def bernstein(p, degree=(2, 2)):
    assert all(n == 0 and i <= degree[0] and j <= degree[1] for n, i, j in p)
    out = {}
    for k, ell in product(range(degree[0] + 1), range(degree[1] + 1)):
        out[k, ell] = sum((a * F(comb(k, i), comb(degree[0], i)) *
                          F(comb(ell, j), comb(degree[1], j))
                          for (_, i, j), a in p.items() if i <= k and j <= ell), F(0))
    return out


def from_bernstein(values, degree=(2, 2)):
    # Independently reconstruct the power polynomial from the recorded basis.
    out = {}
    for (k, ell), a in values.items():
        for i in range(degree[0] - k + 1):
            for j in range(degree[1] - ell + 1):
                m = (0, k + i, ell + j)
                v = a * comb(degree[0], k) * comb(degree[1], ell)
                v *= comb(degree[0] - k, i) * comb(degree[1] - ell, j) * (-1) ** (i + j)
                out[m] = out.get(m, F(0)) + v
    return {m: v for m, v in out.items() if v}


def decode_tensor_certificate(records, degree=(2, 2)):
    grid = set(product(range(degree[0] + 1), range(degree[1] + 1)))
    assert {(k, ell) for k, ell, _ in records} == grid
    out = {}
    for k, ell, arr in records:
        assert len(arr) == len({(a, b) for a, b, _ in arr})
        for a, b, value in arr:
            out.setdefault((a, b), {})[k, ell] = F(value)
    return {key: {index: values.get(index, F(0))
                  for index in grid}
            for key, values in out.items()}


def check_complete_tensor(actual, recorded, degree=(2, 2)):
    saved = decode_tensor_certificate(recorded, degree)
    assert set(actual) == set(saved), (set(actual) - set(saved), set(saved) - set(actual))
    count = 0
    zeros = 0
    minimum = None
    for index, poly in actual.items():
        expected = bernstein(poly, degree)
        assert expected == saved[index], (index, expected, saved[index])
        assert from_bernstein(saved[index], degree) == poly
        assert all(v >= 0 for v in expected.values())
        count += (degree[0] + 1) * (degree[1] + 1)
        zeros += sum(v == 0 for v in expected.values())
        nonzero = [v for v in expected.values() if v]
        if nonzero:
            local = min(nonzero)
            minimum = local if minimum is None else min(minimum, local)
    return count, zeros, str(minimum)


def check_supported_defects(p, recorded, degree, box=(2, 2)):
    assert max(abs(n) for n, _, _ in p) == degree
    saved = {}
    if box == (2, 2):
        for k, ell, values in recorded:
            assert len(values) == degree + 1
            for n, v in enumerate(values):
                saved[n, k, ell] = F(v)
    else:
        for k, values in recorded:
            assert len(values) == degree + 1
            for n, v in enumerate(values):
                saved[n, k, 0] = F(v)
    count = 0
    for n in range(degree + 1):
        poly = defect(p, n)
        coeffs = bernstein(poly, box)
        assert all(v > 0 for v in coeffs.values()), (n, coeffs)
        for (k, ell), value in coeffs.items():
            assert saved[n, k, ell] == value
        assert from_bernstein(coeffs, box) == poly
        count += len(coeffs)
    assert len(saved) == count
    return count


def actual_states():
    x = {(1, 0, 0): F(1)}
    X, Y = constant(1), plus(x, constant(2))
    C = plus(scaled(power(x, 2), 2), scaled(x, 6), constant(5))
    U, V = original_mutation(X, Y, C, x)
    triples = [('root', X, Y, C), ('first-short', X, C, U), ('first-long', Y, C, V)]
    result = {}
    for label, X, Y, C in triples:
        outgoing, _ = original_mutation(X, Y, C, x)
        e = quotient_y(minus(Y, X))
        c = quotient_y(minus(outgoing, X))
        T = minus(scaled(times(plus(x, constant(1)), C), 3), x)
        assert all(v > 0 for p in (e, c, T) for v in ordinary_coeffs(p))
        result[label] = (T, c, e)
    return result


def main():
    source = HERE / 'quantitative_midpoint_bernstein_results.json'
    concise = json.loads(source.read_text())
    archive = HERE / concise['full_certificate']['file']
    compressed = archive.read_bytes()
    payload = gzip.decompress(compressed)
    assert hashlib.sha256(compressed).hexdigest() == concise['full_certificate']['gzip_sha256']
    assert hashlib.sha256(payload).hexdigest() == concise['full_certificate']['uncompressed_sha256']
    assert len(payload) == concise['full_certificate']['uncompressed_bytes']
    assert len(compressed) == concise['full_certificate']['gzip_bytes']
    data = json.loads(payload)
    states = actual_states()
    U = {(0, 1, 0): F(1)}
    V = {(0, 0, 1): F(1)}
    r = minus(constant(2), scaled(U, 4))
    s = minus(constant(2), scaled(V, 4))
    delta2 = power(scaled(minus(r, s), F(1, 2)), 2)
    output = []
    full_count = defect_count = other_tensor_count = 0
    for rec in data['records']:
        label = rec['state']
        T0, c0, e0 = states[label]
        b00, b10 = (c0, e0) if rec['orientation'] == 'forward' else (e0, c0)
        assert ordinary_coeffs(T0) == list(map(F, rec['trace_T']))
        assert ordinary_coeffs(b00) == list(map(F, rec['seed_b0']))
        assert ordinary_coeffs(b10) == list(map(F, rec['seed_b1']))
        assert len(ordinary_coeffs(b10)) - 1 < len(ordinary_coeffs(b00)) + len(ordinary_coeffs(T0)) - 2
        p0 = minus(T0, constant(2))
        Lcorner = plus(times(b00, p0), b10)
        Hcorner = times(p0, Lcorner)
        if rec['smoothed']:
            ordinary_y = {(0, 0, 0): F(1), (1, 0, 0): F(1)}
            Lcorner, Hcorner = (times(ordinary_y, p) for p in (Lcorner, Hcorner))
        assert all(v > 0 for p in (p0, Lcorner, Hcorner) for v in ordinary_coeffs(p))
        assert ordinary_coeffs(Lcorner) == list(map(F, rec['support']['corner_L2_ordinary_coefficients']))
        assert ordinary_coeffs(Hcorner) == list(map(F, rec['support']['corner_H22_ordinary_coefficients']))
        T, b0, b1 = map(laurent, (T0, b00, b10))
        Tr, Ts = minus(T, r), minus(T, s)
        H = plus(times(times(b0, Tr), Ts),
                 times(b1, minus(T, scaled(plus(r, s), F(1, 2)))))
        L = plus(times(b0, Tr), b1)
        reference = b1
        if rec['smoothed']:
            H, L, reference = (times(LAURENT_Y, p) for p in (H, L, reference))
        TH, TB = tensor(H), tensor(reference)
        ch, _, _ = check_complete_tensor(TH, rec['complete_H_bernstein_arrays'])
        cl, _, _ = check_complete_tensor(tensor(L), rec['L_defects']['complete_all_character_bernstein'], (2, 0))
        other_tensor_count += ch + cl
        sharp = {key: p for key in set(TH) | set(TB)
                 if (p := minus(TH.get(key, {}), times(delta2, TB.get(key, {}))))}
        uniform = tensor_minus(TH, TB, 4)
        cs, zs, ms = check_complete_tensor(sharp, rec['complete_sharp_bernstein_arrays'])
        cu, zu, mu = check_complete_tensor(uniform, rec['complete_uniform4_bernstein_arrays'])
        assert cs == rec['sharp_relative_all_characters']['coefficients']
        assert cu == rec['uniform4_relative_all_characters']['coefficients']
        assert zs == rec['sharp_relative_all_characters']['zeros']
        assert zu == rec['uniform4_relative_all_characters']['zeros']
        assert F(ms) == F(rec['sharp_relative_all_characters']['minimum_nonzero']['value'])
        assert F(mu) == F(rec['uniform4_relative_all_characters']['minimum_nonzero']['value'])
        dh = check_supported_defects(H, rec['H_defects']['complete_supported_defect_bernstein'], rec['degree_H'])
        dl = check_supported_defects(L, rec['L_defects']['complete_supported_defect_bernstein'], rec['L_defects']['degree'], (2, 0))
        full_count += cs + cu
        defect_count += dh + dl
        output.append({'state': label, 'orientation': rec['orientation'], 'smoothed': rec['smoothed'],
                       'degree_H': rec['degree_H'], 'degree_L': rec['L_defects']['degree'],
                       'full_relative_Bernstein_coefficients': cs + cu,
                       'pure_L_H_all_character_coefficients': ch + cl,
                       'all_supported_strict_defect_coefficients': dh + dl,
                       'uniform4_minimum_nonzero': mu, 'PASS': True})
    assert len(output) == 12
    trace_count = 0
    for rec in data['traces']:
        T0, _, _ = states[rec['state']]
        trace = minus(laurent(T0), r)
        assert ordinary_coeffs(T0) == list(map(F, rec['trace']))
        trace_count += check_supported_defects(trace, rec['certificate']['complete_supported_defect_bernstein'], rec['certificate']['degree'], (2, 0))
        ct, _, _ = check_complete_tensor(tensor(trace), rec['certificate']['complete_all_character_bernstein'], (2, 0))
        other_tensor_count += ct
    result = {'status': 'PASS_INDEPENDENT_EXACT_FULL_CUBE_RECONSTRUCTION',
              'actual_base_states': list(states), 'records': output,
              'full_relative_Bernstein_coefficients_verified': full_count,
              'strict_L_H_Bernstein_coefficients_verified': defect_count,
              'strict_trace_Bernstein_coefficients_verified': trace_count,
              'pure_L_H_trace_all_character_coefficients_verified': other_tensor_count,
              'parameter_cube': 'r=2-4u, s=2-4v, 0<=u,v<=1',
              'support_degree_check': 'Strict degree seed condition checked separately in both orientations; ordinary base coefficients positive.',
              'source_results_sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
              'source_archive_sha256': hashlib.sha256(compressed).hexdigest(),
              'source_full_payload_sha256': hashlib.sha256(payload).hexdigest(),
              'independence': 'No producer imports; original scalar mutations, direct Laurent parameter expansion, complete inverse Bernstein reconstruction.',
              'consequence': 'Root and both first children satisfy uniform-4 paired MP2 on the complete parameter continuum, conditional on the independently proved all-minor character theorem.',
              'changed_center_BOTH_closure': 'OPEN', 'full_tree_Local_TP2': 'OPEN'}
    target = HERE / 'audit_midpoint_base_results.json'
    target.write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps({k: v for k, v in result.items() if k != 'records'}, indent=2))


if __name__ == '__main__':
    main()
